package com.kk.configurationservice.model;

import com.azure.spring.data.cosmos.core.mapping.Container;
import lombok.*;
import org.springframework.data.annotation.Id;

@Data
@Container(containerName = "Configurations") // Cosmos DB container name
@Getter
@Setter
@RequiredArgsConstructor
public class Configuration {

    @Id
    private String id; // Cosmos DB requires the id to be a String type (can be autogenerated or set explicitly)

    private String sourceType;
    private String sourceDetails;
    private String trigger;
    private String triggerDetails;
    private String action;
    private String destinationType;
    private String destinationDetails;

}
